flyway.cleanDisabled=false
flyway.locations=filesystem:src/main/resources/db/migration
flyway.defaultSchema=public
flyway.schemas=public
flyway.url=jdbc:postgresql://localhost:5432/dev-merchant-checker
flyway.user=dev-bobby
flyway.password=dev-bobby