spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-merchant-checker
    username: dev-bobby
    password: dev-bobby
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none