spring:
  cache:
    type: redis
  application:
    name: merchant-checker-service
  flyway:
    locations: classpath:/db/migration
    baselineOnMigrate: true
    enabled: true
    schemas: public
    default-schema: public
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC # sets zonedDateTime to UTC
  docker:
    compose:
      enabled: false