CREATE TABLE merchant
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(255)                             NOT NULL,
    mcc             INTEGER                                  NOT NULL,
    description     VARCHAR(255)                             NOT NULL,
    mode_of_payment merchant_mode_of_payment_type                                 NOT NULL,
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);