DROP TYPE merchant_mode_of_payment_type CASCADE;

DROP TABLE merchant;

CREATE TYPE merchant_mode_of_payment_type AS ENUM ('ONLINE_WEB','ONLINE_IN_APP','ONLINE_SHOPBACKPAY','ONLINE_FAVEPAY','ONLINE_KRISPAY','OFFLINE_MOBILE_WALLET','OFFLINE_PHYSICAL_CARD');

CREATE TABLE merchant
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    name            VARCHAR(255)                             NOT NULL,
    mcc             BIGINT                                   NOT NULL,
    description     VARCHAR(255)                             NOT NULL,
    mode_of_payment merchant_mode_of_payment_type         NOT NULL,
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);